/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#cbe7f5",
        "on-primary-container": "#8abda9",
        "surface-tint": "#376757",
        "surface-container-high": "#d1ecfa",
        "surface": "#f3faff",
        "primary-fixed": "#baeed9",
        "surface-dim": "#c3deec",
        "secondary-container": "#67bafd",
        "on-secondary-container": "#004972",
        "surface-bright": "#f3faff",
        "tertiary": "#650007",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#e6f6ff",
        "secondary-fixed": "#cde5ff",
        "on-secondary-fixed-variant": "#004b74",
        "outline": "#707974",
        "primary-fixed-dim": "#9ed1bd",
        "inverse-surface": "#19343e",
        "on-secondary-fixed": "#001d32",
        "on-tertiary-container": "#ff958c",
        "background": "#f3faff",
        "surface-container": "#d8f2ff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb3ac",
        "tertiary-fixed": "#ffdad6",
        "on-background": "#021f29",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#1d4f40",
        "primary": "#003629",
        "on-surface": "#021f29",
        "on-primary": "#ffffff",
        "outline-variant": "#c0c9c3",
        "surface-variant": "#cbe7f5",
        "inverse-on-surface": "#dff4ff",
        "secondary-fixed-dim": "#94ccff",
        "secondary": "#006399",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#8f000f",
        "inverse-primary": "#9ed1bd",
        "on-tertiary-fixed": "#410003",
        "primary-container": "#1b4d3e",
        "on-surface-variant": "#404945",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#002117",
        "on-tertiary-fixed-variant": "#930010"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
